global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'group-buy-market-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - '172.30.0.4:8091'
        labels:
          app: 'group-buy-market-app'
